import { IFilterItem } from '@/types/ICommon';

export const headerLinks = ['/anime', '/manga', '/characters'];
export const headerPages = ['Anime', 'Manga', 'Characters'];

export const animeFilterOptions: IFilterItem[] = [
  {
    mal_id: 1,
    name: 'Action',
    url: 'https://myanimelist.net/anime/genre/1/Action',
    count: 5006,
  },
  {
    mal_id: 2,
    name: 'Adventure',
    url: 'https://myanimelist.net/anime/genre/2/Adventure',
    count: 3978,
  },
  {
    mal_id: 5,
    name: 'Avant Garde',
    url: 'https://myanimelist.net/anime/genre/5/Avant_Garde',
    count: 855,
  },
  {
    mal_id: 46,
    name: 'Award Winning',
    url: 'https://myanimelist.net/anime/genre/46/Award_Winning',
    count: 241,
  },
  {
    mal_id: 28,
    name: 'Boys Love',
    url: 'https://myanimelist.net/anime/genre/28/Boys_Love',
    count: 174,
  },
  {
    mal_id: 4,
    name: 'Comedy',
    url: 'https://myanimelist.net/anime/genre/4/Comedy',
    count: 7219,
  },
  {
    mal_id: 8,
    name: 'Drama',
    url: 'https://myanimelist.net/anime/genre/8/Drama',
    count: 2904,
  },
  {
    mal_id: 10,
    name: 'Fantasy',
    url: 'https://myanimelist.net/anime/genre/10/Fantasy',
    count: 5579,
  },
  {
    mal_id: 26,
    name: 'Girls Love',
    url: 'https://myanimelist.net/anime/genre/26/Girls_Love',
    count: 107,
  },
  {
    mal_id: 47,
    name: 'Gourmet',
    url: 'https://myanimelist.net/anime/genre/47/Gourmet',
    count: 165,
  },
  {
    mal_id: 14,
    name: 'Horror',
    url: 'https://myanimelist.net/anime/genre/14/Horror',
    count: 544,
  },
  {
    mal_id: 7,
    name: 'Mystery',
    url: 'https://myanimelist.net/anime/genre/7/Mystery',
    count: 890,
  },
  {
    mal_id: 22,
    name: 'Romance',
    url: 'https://myanimelist.net/anime/genre/22/Romance',
    count: 2034,
  },
  {
    mal_id: 24,
    name: 'Sci-Fi',
    url: 'https://myanimelist.net/anime/genre/24/Sci-Fi',
    count: 3203,
  },
  {
    mal_id: 36,
    name: 'Slice of Life',
    url: 'https://myanimelist.net/anime/genre/36/Slice_of_Life',
    count: 1628,
  },
  {
    mal_id: 30,
    name: 'Sports',
    url: 'https://myanimelist.net/anime/genre/30/Sports',
    count: 772,
  },
  {
    mal_id: 37,
    name: 'Supernatural',
    url: 'https://myanimelist.net/anime/genre/37/Supernatural',
    count: 1491,
  },
  {
    mal_id: 41,
    name: 'Suspense',
    url: 'https://myanimelist.net/anime/genre/41/Suspense',
    count: 278,
  },
  {
    mal_id: 9,
    name: 'Ecchi',
    url: 'https://myanimelist.net/anime/genre/9/Ecchi',
    count: 791,
  },
  {
    mal_id: 49,
    name: 'Erotica',
    url: 'https://myanimelist.net/anime/genre/49/Erotica',
    count: 71,
  },
  {
    mal_id: 12,
    name: 'Hentai',
    url: 'https://myanimelist.net/anime/genre/12/Hentai',
    count: 1505,
  },
  {
    mal_id: 50,
    name: 'Adult Cast',
    url: 'https://myanimelist.net/anime/genre/50/Adult_Cast',
    count: 570,
  },
  {
    mal_id: 51,
    name: 'Anthropomorphic',
    url: 'https://myanimelist.net/anime/genre/51/Anthropomorphic',
    count: 934,
  },
  {
    mal_id: 52,
    name: 'CGDCT',
    url: 'https://myanimelist.net/anime/genre/52/CGDCT',
    count: 235,
  },
  {
    mal_id: 53,
    name: 'Childcare',
    url: 'https://myanimelist.net/anime/genre/53/Childcare',
    count: 69,
  },
  {
    mal_id: 54,
    name: 'Combat Sports',
    url: 'https://myanimelist.net/anime/genre/54/Combat_Sports',
    count: 91,
  },
  {
    mal_id: 81,
    name: 'Crossdressing',
    url: 'https://myanimelist.net/anime/genre/81/Crossdressing',
    count: 48,
  },
  {
    mal_id: 55,
    name: 'Delinquents',
    url: 'https://myanimelist.net/anime/genre/55/Delinquents',
    count: 69,
  },
  {
    mal_id: 39,
    name: 'Detective',
    url: 'https://myanimelist.net/anime/genre/39/Detective',
    count: 310,
  },
  {
    mal_id: 56,
    name: 'Educational',
    url: 'https://myanimelist.net/anime/genre/56/Educational',
    count: 269,
  },
  {
    mal_id: 57,
    name: 'Gag Humor',
    url: 'https://myanimelist.net/anime/genre/57/Gag_Humor',
    count: 241,
  },
  {
    mal_id: 58,
    name: 'Gore',
    url: 'https://myanimelist.net/anime/genre/58/Gore',
    count: 253,
  },
  {
    mal_id: 35,
    name: 'Harem',
    url: 'https://myanimelist.net/anime/genre/35/Harem',
    count: 462,
  },
  {
    mal_id: 59,
    name: 'High Stakes Game',
    url: 'https://myanimelist.net/anime/genre/59/High_Stakes_Game',
    count: 47,
  },
  {
    mal_id: 13,
    name: 'Historical',
    url: 'https://myanimelist.net/anime/genre/13/Historical',
    count: 1533,
  },
  {
    mal_id: 60,
    name: 'Idols (Female)',
    url: 'https://myanimelist.net/anime/genre/60/Idols_Female',
    count: 304,
  },
  {
    mal_id: 61,
    name: 'Idols (Male)',
    url: 'https://myanimelist.net/anime/genre/61/Idols_Male',
    count: 170,
  },
  {
    mal_id: 62,
    name: 'Isekai',
    url: 'https://myanimelist.net/anime/genre/62/Isekai',
    count: 344,
  },
  {
    mal_id: 63,
    name: 'Iyashikei',
    url: 'https://myanimelist.net/anime/genre/63/Iyashikei',
    count: 169,
  },
  {
    mal_id: 64,
    name: 'Love Polygon',
    url: 'https://myanimelist.net/anime/genre/64/Love_Polygon',
    count: 90,
  },
  {
    mal_id: 65,
    name: 'Magical Sex Shift',
    url: 'https://myanimelist.net/anime/genre/65/Magical_Sex_Shift',
    count: 30,
  },
  {
    mal_id: 66,
    name: 'Mahou Shoujo',
    url: 'https://myanimelist.net/anime/genre/66/Mahou_Shoujo',
    count: 331,
  },
  {
    mal_id: 17,
    name: 'Martial Arts',
    url: 'https://myanimelist.net/anime/genre/17/Martial_Arts',
    count: 605,
  },
  {
    mal_id: 18,
    name: 'Mecha',
    url: 'https://myanimelist.net/anime/genre/18/Mecha',
    count: 1271,
  },
  {
    mal_id: 67,
    name: 'Medical',
    url: 'https://myanimelist.net/anime/genre/67/Medical',
    count: 44,
  },
  {
    mal_id: 38,
    name: 'Military',
    url: 'https://myanimelist.net/anime/genre/38/Military',
    count: 702,
  },
  {
    mal_id: 19,
    name: 'Music',
    url: 'https://myanimelist.net/anime/genre/19/Music',
    count: 4131,
  },
  {
    mal_id: 6,
    name: 'Mythology',
    url: 'https://myanimelist.net/anime/genre/6/Mythology',
    count: 640,
  },
  {
    mal_id: 68,
    name: 'Organized Crime',
    url: 'https://myanimelist.net/anime/genre/68/Organized_Crime',
    count: 85,
  },
  {
    mal_id: 69,
    name: 'Otaku Culture',
    url: 'https://myanimelist.net/anime/genre/69/Otaku_Culture',
    count: 92,
  },
  {
    mal_id: 20,
    name: 'Parody',
    url: 'https://myanimelist.net/anime/genre/20/Parody',
    count: 758,
  },
  {
    mal_id: 70,
    name: 'Performing Arts',
    url: 'https://myanimelist.net/anime/genre/70/Performing_Arts',
    count: 118,
  },
  {
    mal_id: 71,
    name: 'Pets',
    url: 'https://myanimelist.net/anime/genre/71/Pets',
    count: 107,
  },
  {
    mal_id: 40,
    name: 'Psychological',
    url: 'https://myanimelist.net/anime/genre/40/Psychological',
    count: 419,
  },
  {
    mal_id: 3,
    name: 'Racing',
    url: 'https://myanimelist.net/anime/genre/3/Racing',
    count: 249,
  },
  {
    mal_id: 72,
    name: 'Reincarnation',
    url: 'https://myanimelist.net/anime/genre/72/Reincarnation',
    count: 136,
  },
  {
    mal_id: 73,
    name: 'Reverse Harem',
    url: 'https://myanimelist.net/anime/genre/73/Reverse_Harem',
    count: 75,
  },
  {
    mal_id: 74,
    name: 'Romantic Subtext',
    url: 'https://myanimelist.net/anime/genre/74/Romantic_Subtext',
    count: 55,
  },
  {
    mal_id: 21,
    name: 'Samurai',
    url: 'https://myanimelist.net/anime/genre/21/Samurai',
    count: 235,
  },
  {
    mal_id: 23,
    name: 'School',
    url: 'https://myanimelist.net/anime/genre/23/School',
    count: 2015,
  },
  {
    mal_id: 75,
    name: 'Showbiz',
    url: 'https://myanimelist.net/anime/genre/75/Showbiz',
    count: 38,
  },
  {
    mal_id: 29,
    name: 'Space',
    url: 'https://myanimelist.net/anime/genre/29/Space',
    count: 623,
  },
  {
    mal_id: 11,
    name: 'Strategy Game',
    url: 'https://myanimelist.net/anime/genre/11/Strategy_Game',
    count: 324,
  },
  {
    mal_id: 31,
    name: 'Super Power',
    url: 'https://myanimelist.net/anime/genre/31/Super_Power',
    count: 702,
  },
  {
    mal_id: 76,
    name: 'Survival',
    url: 'https://myanimelist.net/anime/genre/76/Survival',
    count: 93,
  },
  {
    mal_id: 77,
    name: 'Team Sports',
    url: 'https://myanimelist.net/anime/genre/77/Team_Sports',
    count: 306,
  },
  {
    mal_id: 78,
    name: 'Time Travel',
    url: 'https://myanimelist.net/anime/genre/78/Time_Travel',
    count: 145,
  },
  {
    mal_id: 32,
    name: 'Vampire',
    url: 'https://myanimelist.net/anime/genre/32/Vampire',
    count: 165,
  },
  {
    mal_id: 79,
    name: 'Video Game',
    url: 'https://myanimelist.net/anime/genre/79/Video_Game',
    count: 146,
  },
  {
    mal_id: 80,
    name: 'Visual Arts',
    url: 'https://myanimelist.net/anime/genre/80/Visual_Arts',
    count: 90,
  },
  {
    mal_id: 48,
    name: 'Workplace',
    url: 'https://myanimelist.net/anime/genre/48/Workplace',
    count: 190,
  },
  {
    mal_id: 43,
    name: 'Josei',
    url: 'https://myanimelist.net/anime/genre/43/Josei',
    count: 154,
  },
  {
    mal_id: 15,
    name: 'Kids',
    url: 'https://myanimelist.net/anime/genre/15/Kids',
    count: 6341,
  },
  {
    mal_id: 42,
    name: 'Seinen',
    url: 'https://myanimelist.net/anime/genre/42/Seinen',
    count: 999,
  },
  {
    mal_id: 25,
    name: 'Shoujo',
    url: 'https://myanimelist.net/anime/genre/25/Shoujo',
    count: 477,
  },
  {
    mal_id: 27,
    name: 'Shounen',
    url: 'https://myanimelist.net/anime/genre/27/Shounen',
    count: 1927,
  },
];
export const animeRatingOptions: IFilterItem[] = [
  {
    mal_id: 'g',
    name: 'G',
  },
  {
    mal_id: 'pg',
    name: 'PG',
  },
  {
    mal_id: 'pg13',
    name: 'PG-13',
  },
  {
    mal_id: 'r17',
    name: 'R-17',
  },
  {
    mal_id: 'r',
    name: 'R',
  },
  {
    mal_id: 'rx',
    name: 'Rx',
  },
];
export const animeStatusOptions: IFilterItem[] = [
  {
    mal_id: 'airing',
    name: 'Airing',
  },
  {
    mal_id: 'complete',
    name: 'Complete',
  },
  {
    mal_id: 'upcoming',
    name: 'Upcoming',
  },
];
export const animeTypeOptions: IFilterItem[] = [
  {
    mal_id: 'tv',
    name: 'TV',
  },
  {
    mal_id: 'movie',
    name: 'Movie',
  },
  {
    mal_id: 'ova',
    name: 'OVA',
  },
  {
    mal_id: 'ona',
    name: 'ONA',
  },
  {
    mal_id: 'special',
    name: 'Special',
  },
  {
    mal_id: 'music',
    name: 'Music',
  },
];
export const sortOptions: IFilterItem[] = [
  {
    mal_id: 'start_date',
    name: 'Start date',
  },
  {
    mal_id: 'end_date',
    name: 'End date',
  },
  {
    mal_id: 'popularity',
    name: 'Popularity',
  },
  {
    mal_id: 'rank',
    name: 'Rank',
  },
  {
    mal_id: 'title',
    name: 'Title',
  },
];

// =======================================================================================

export const mangaFilterOptions: IFilterItem[] = [
  {
    mal_id: 1,
    name: 'Action',
    url: 'https://myanimelist.net/manga/genre/1/Action',
    count: 9206,
  },
  {
    mal_id: 2,
    name: 'Adventure',
    url: 'https://myanimelist.net/manga/genre/2/Adventure',
    count: 4026,
  },
  {
    mal_id: 5,
    name: 'Avant Garde',
    url: 'https://myanimelist.net/manga/genre/5/Avant_Garde',
    count: 73,
  },
  {
    mal_id: 46,
    name: 'Award Winning',
    url: 'https://myanimelist.net/manga/genre/46/Award_Winning',
    count: 439,
  },
  {
    mal_id: 28,
    name: 'Boys Love',
    url: 'https://myanimelist.net/manga/genre/28/Boys_Love',
    count: 9951,
  },
  {
    mal_id: 4,
    name: 'Comedy',
    url: 'https://myanimelist.net/manga/genre/4/Comedy',
    count: 14447,
  },
  {
    mal_id: 8,
    name: 'Drama',
    url: 'https://myanimelist.net/manga/genre/8/Drama',
    count: 9619,
  },
  {
    mal_id: 10,
    name: 'Fantasy',
    url: 'https://myanimelist.net/manga/genre/10/Fantasy',
    count: 11435,
  },
  {
    mal_id: 26,
    name: 'Girls Love',
    url: 'https://myanimelist.net/manga/genre/26/Girls_Love',
    count: 1654,
  },
  {
    mal_id: 47,
    name: 'Gourmet',
    url: 'https://myanimelist.net/manga/genre/47/Gourmet',
    count: 444,
  },
  {
    mal_id: 14,
    name: 'Horror',
    url: 'https://myanimelist.net/manga/genre/14/Horror',
    count: 1731,
  },
  {
    mal_id: 7,
    name: 'Mystery',
    url: 'https://myanimelist.net/manga/genre/7/Mystery',
    count: 2498,
  },
  {
    mal_id: 22,
    name: 'Romance',
    url: 'https://myanimelist.net/manga/genre/22/Romance',
    count: 17291,
  },
  {
    mal_id: 24,
    name: 'Sci-Fi',
    url: 'https://myanimelist.net/manga/genre/24/Sci-Fi',
    count: 3295,
  },
  {
    mal_id: 36,
    name: 'Slice of Life',
    url: 'https://myanimelist.net/manga/genre/36/Slice_of_Life',
    count: 5227,
  },
  {
    mal_id: 30,
    name: 'Sports',
    url: 'https://myanimelist.net/manga/genre/30/Sports',
    count: 1157,
  },
  {
    mal_id: 37,
    name: 'Supernatural',
    url: 'https://myanimelist.net/manga/genre/37/Supernatural',
    count: 7670,
  },
  {
    mal_id: 45,
    name: 'Suspense',
    url: 'https://myanimelist.net/manga/genre/45/Suspense',
    count: 564,
  },
  {
    mal_id: 9,
    name: 'Ecchi',
    url: 'https://myanimelist.net/manga/genre/9/Ecchi',
    count: 3611,
  },
  {
    mal_id: 49,
    name: 'Erotica',
    url: 'https://myanimelist.net/manga/genre/49/Erotica',
    count: 9155,
  },
  {
    mal_id: 12,
    name: 'Hentai',
    url: 'https://myanimelist.net/manga/genre/12/Hentai',
    count: 11388,
  },
  {
    mal_id: 50,
    name: 'Adult Cast',
    url: 'https://myanimelist.net/manga/genre/50/Adult_Cast',
    count: 697,
  },
  {
    mal_id: 51,
    name: 'Anthropomorphic',
    url: 'https://myanimelist.net/manga/genre/51/Anthropomorphic',
    count: 195,
  },
  {
    mal_id: 52,
    name: 'CGDCT',
    url: 'https://myanimelist.net/manga/genre/52/CGDCT',
    count: 142,
  },
  {
    mal_id: 53,
    name: 'Childcare',
    url: 'https://myanimelist.net/manga/genre/53/Childcare',
    count: 189,
  },
  {
    mal_id: 54,
    name: 'Combat Sports',
    url: 'https://myanimelist.net/manga/genre/54/Combat_Sports',
    count: 169,
  },
  {
    mal_id: 44,
    name: 'Crossdressing',
    url: 'https://myanimelist.net/manga/genre/44/Crossdressing',
    count: 617,
  },
  {
    mal_id: 55,
    name: 'Delinquents',
    url: 'https://myanimelist.net/manga/genre/55/Delinquents',
    count: 167,
  },
  {
    mal_id: 39,
    name: 'Detective',
    url: 'https://myanimelist.net/manga/genre/39/Detective',
    count: 403,
  },
  {
    mal_id: 56,
    name: 'Educational',
    url: 'https://myanimelist.net/manga/genre/56/Educational',
    count: 47,
  },
  {
    mal_id: 57,
    name: 'Gag Humor',
    url: 'https://myanimelist.net/manga/genre/57/Gag_Humor',
    count: 211,
  },
  {
    mal_id: 58,
    name: 'Gore',
    url: 'https://myanimelist.net/manga/genre/58/Gore',
    count: 179,
  },
  {
    mal_id: 35,
    name: 'Harem',
    url: 'https://myanimelist.net/manga/genre/35/Harem',
    count: 2291,
  },
  {
    mal_id: 59,
    name: 'High Stakes Game',
    url: 'https://myanimelist.net/manga/genre/59/High_Stakes_Game',
    count: 83,
  },
  {
    mal_id: 13,
    name: 'Historical',
    url: 'https://myanimelist.net/manga/genre/13/Historical',
    count: 2489,
  },
  {
    mal_id: 60,
    name: 'Idols (Female)',
    url: 'https://myanimelist.net/manga/genre/60/Idols_Female',
    count: 49,
  },
  {
    mal_id: 61,
    name: 'Idols (Male)',
    url: 'https://myanimelist.net/manga/genre/61/Idols_Male',
    count: 52,
  },
  {
    mal_id: 62,
    name: 'Isekai',
    url: 'https://myanimelist.net/manga/genre/62/Isekai',
    count: 1118,
  },
  {
    mal_id: 63,
    name: 'Iyashikei',
    url: 'https://myanimelist.net/manga/genre/63/Iyashikei',
    count: 144,
  },
  {
    mal_id: 64,
    name: 'Love Polygon',
    url: 'https://myanimelist.net/manga/genre/64/Love_Polygon',
    count: 265,
  },
  {
    mal_id: 65,
    name: 'Magical Sex Shift',
    url: 'https://myanimelist.net/manga/genre/65/Magical_Sex_Shift',
    count: 243,
  },
  {
    mal_id: 66,
    name: 'Mahou Shoujo',
    url: 'https://myanimelist.net/manga/genre/66/Mahou_Shoujo',
    count: 149,
  },
  {
    mal_id: 17,
    name: 'Martial Arts',
    url: 'https://myanimelist.net/manga/genre/17/Martial_Arts',
    count: 692,
  },
  {
    mal_id: 18,
    name: 'Mecha',
    url: 'https://myanimelist.net/manga/genre/18/Mecha',
    count: 719,
  },
  {
    mal_id: 67,
    name: 'Medical',
    url: 'https://myanimelist.net/manga/genre/67/Medical',
    count: 162,
  },
  {
    mal_id: 68,
    name: 'Memoir',
    url: 'https://myanimelist.net/manga/genre/68/Memoir',
    count: 192,
  },
  {
    mal_id: 38,
    name: 'Military',
    url: 'https://myanimelist.net/manga/genre/38/Military',
    count: 715,
  },
  {
    mal_id: 19,
    name: 'Music',
    url: 'https://myanimelist.net/manga/genre/19/Music',
    count: 533,
  },
  {
    mal_id: 6,
    name: 'Mythology',
    url: 'https://myanimelist.net/manga/genre/6/Mythology',
    count: 802,
  },
  {
    mal_id: 69,
    name: 'Organized Crime',
    url: 'https://myanimelist.net/manga/genre/69/Organized_Crime',
    count: 153,
  },
  {
    mal_id: 70,
    name: 'Otaku Culture',
    url: 'https://myanimelist.net/manga/genre/70/Otaku_Culture',
    count: 112,
  },
  {
    mal_id: 20,
    name: 'Parody',
    url: 'https://myanimelist.net/manga/genre/20/Parody',
    count: 330,
  },
  {
    mal_id: 71,
    name: 'Performing Arts',
    url: 'https://myanimelist.net/manga/genre/71/Performing_Arts',
    count: 119,
  },
  {
    mal_id: 72,
    name: 'Pets',
    url: 'https://myanimelist.net/manga/genre/72/Pets',
    count: 143,
  },
  {
    mal_id: 40,
    name: 'Psychological',
    url: 'https://myanimelist.net/manga/genre/40/Psychological',
    count: 1577,
  },
  {
    mal_id: 3,
    name: 'Racing',
    url: 'https://myanimelist.net/manga/genre/3/Racing',
    count: 78,
  },
  {
    mal_id: 73,
    name: 'Reincarnation',
    url: 'https://myanimelist.net/manga/genre/73/Reincarnation',
    count: 759,
  },
  {
    mal_id: 74,
    name: 'Reverse Harem',
    url: 'https://myanimelist.net/manga/genre/74/Reverse_Harem',
    count: 149,
  },
  {
    mal_id: 75,
    name: 'Romantic Subtext',
    url: 'https://myanimelist.net/manga/genre/75/Romantic_Subtext',
    count: 311,
  },
  {
    mal_id: 21,
    name: 'Samurai',
    url: 'https://myanimelist.net/manga/genre/21/Samurai',
    count: 271,
  },
  {
    mal_id: 23,
    name: 'School',
    url: 'https://myanimelist.net/manga/genre/23/School',
    count: 11082,
  },
  {
    mal_id: 76,
    name: 'Showbiz',
    url: 'https://myanimelist.net/manga/genre/76/Showbiz',
    count: 132,
  },
  {
    mal_id: 29,
    name: 'Space',
    url: 'https://myanimelist.net/manga/genre/29/Space',
    count: 264,
  },
  {
    mal_id: 11,
    name: 'Strategy Game',
    url: 'https://myanimelist.net/manga/genre/11/Strategy_Game',
    count: 299,
  },
  {
    mal_id: 31,
    name: 'Super Power',
    url: 'https://myanimelist.net/manga/genre/31/Super_Power',
    count: 620,
  },
  {
    mal_id: 77,
    name: 'Survival',
    url: 'https://myanimelist.net/manga/genre/77/Survival',
    count: 141,
  },
  {
    mal_id: 78,
    name: 'Team Sports',
    url: 'https://myanimelist.net/manga/genre/78/Team_Sports',
    count: 431,
  },
  {
    mal_id: 79,
    name: 'Time Travel',
    url: 'https://myanimelist.net/manga/genre/79/Time_Travel',
    count: 497,
  },
  {
    mal_id: 32,
    name: 'Vampire',
    url: 'https://myanimelist.net/manga/genre/32/Vampire',
    count: 526,
  },
  {
    mal_id: 80,
    name: 'Video Game',
    url: 'https://myanimelist.net/manga/genre/80/Video_Game',
    count: 292,
  },
  {
    mal_id: 81,
    name: 'Villainess',
    url: 'https://myanimelist.net/manga/genre/81/Villainess',
    count: 275,
  },
  {
    mal_id: 82,
    name: 'Visual Arts',
    url: 'https://myanimelist.net/manga/genre/82/Visual_Arts',
    count: 92,
  },
  {
    mal_id: 48,
    name: 'Workplace',
    url: 'https://myanimelist.net/manga/genre/48/Workplace',
    count: 376,
  },
  {
    mal_id: 42,
    name: 'Josei',
    url: 'https://myanimelist.net/manga/genre/42/Josei',
    count: 4095,
  },
  {
    mal_id: 15,
    name: 'Kids',
    url: 'https://myanimelist.net/manga/genre/15/Kids',
    count: 275,
  },
  {
    mal_id: 41,
    name: 'Seinen',
    url: 'https://myanimelist.net/manga/genre/41/Seinen',
    count: 7901,
  },
  {
    mal_id: 25,
    name: 'Shoujo',
    url: 'https://myanimelist.net/manga/genre/25/Shoujo',
    count: 8311,
  },
  {
    mal_id: 27,
    name: 'Shounen',
    url: 'https://myanimelist.net/manga/genre/27/Shounen',
    count: 6504,
  },
];
export const mangaStatusOptions: IFilterItem[] = [
  {
    mal_id: 'publishing',
    name: 'Publishing',
  },
  {
    mal_id: 'complete',
    name: 'Complete',
  },
  {
    mal_id: 'hiatus',
    name: 'Hiatus',
  },
  {
    mal_id: 'discontinued',
    name: 'Discontinued',
  },
  {
    mal_id: 'upcoming',
    name: 'Upcoming',
  },
];
export const mangaTypeOptions: IFilterItem[] = [
  {
    mal_id: 'manga',
    name: 'Manga',
  },
  {
    mal_id: 'novel',
    name: 'Novel',
  },
  {
    mal_id: 'lightnovel',
    name: 'Lightnovel',
  },
  {
    mal_id: 'oneshot',
    name: 'Oneshot',
  },
  {
    mal_id: 'doujin',
    name: 'Doujin',
  },
  {
    mal_id: 'manhwa',
    name: 'Manhwa',
  },
  {
    mal_id: 'manhua',
    name: 'Manhua',
  },
];
